### ISSUE TITLE
Basic Auth allows empty user/pass

### ISSUE THREAD

**Issue by fabioxgn** [goji/httpauth#12]
Does it make sense to call `goji.Use(httpauth.SimpleBasicAuth("", ""))` (with empty user/pass)?

I think it could cause security issues, ex: I set the user/pass on env vars, and if I forget to set the vars on the production environment my api runs without authentication.

I think it makes sense to validate if a user and pass is provided to this method, what do you guys think? 

I could send a PR if this makes sense for you.

**Comment by elithrar** [comment]
Sure—I am all for safe defaults.

This library is designed to be reasonably simple, but I think a layer of
protection against a common mistake/error like that is worthwhile. Submit a
PR + a test when you can. Should probably just raise an Unauthorized error
when both are empty.

(thanks!)

**Comment by fabioxgn** [comment]
@elithrar just sent the PR. If you see anything that can be improved, please tell me.

I've implemented it on the most simple way, it verifies the opts before everything else, there is no point in checking headers or anything if the basic user/pass is not set.
