### ISSUE TITLE
Provide an example on how to inject database connection in custom authFunc

### ISSUE THREAD

**Issue by jseguillon** [goji/httpauth#20]
Hello, 
I'm looking for a way to inject a database session when calling custom authFunc. 

Here is the use-case : in main let's open a mongo db connection. How could I inject this connection in my custom authFunc to challenge the password in the database.  

I could open a specific connection inside the authFunc for the challenge but this would not be really good pattern.  

Can you provide hints ? Or should I fork this repo to change arguments in authFunc call ?  

Thanks.

**Comment by elithrar** [comment]
If you have database backed logins, you should be storing bcrypt/scrypt
hashes of those passwords and checking them directly.

I would not suggest using this library for larger-scale needs.

**Comment by jseguillon** [comment]
No large scale need for me. Of course I don't plan to store pass in clear text 😆 but I'd to rely on a lib for headers and user/pass decode before checking crypted hash in DB. Any alternative lib you'd recommend ? 

Regarding the 1st question which aks for a way to inject db connection in custom auth function, should I read in your answer "no this is not possible with this lib" ?

**Comment by elithrar** [comment]
You don't have to pass your DB connection to the AuthFunc - you could provide a custom AuthFunc that is a method on a struct that makes your DB connection available - e.g.

```go
type Env struct {
    DB *sql.DB
     // other fields
}

func (env *Env) AuthFunc (user string, pw string, r *http.Request) bool {
    // Handle the request
}

// elsewhere
env := &Env{DB: dbConn}
opts := httpauth.AuthOptions{
                    Realm: "Restricted",
                    AuthFunc: env.AuthFunc,
                }

goji.Use(httpauth.BasicAuth(opts), SomeOtherMiddleware)
```

Alternatively, you could write some simple middleware that handles this yourself, and remove the dependency:

```go
func AuthMiddleware(env *Env, opts *AuthOptions) func(http.Handler) http.Handler {
    fn := func (next http.Handler) http.Handler {
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
            // 1. Grab the user:pass from the request - e.g in FormValues
           // 2. Lookup in the DB, compare user and password hashes
           // 3. Set a cookie via https://github.com/gorilla/sessions if OK
           // 4. Call next.ServeHTTP(w, r) if successful
           // 5. else, return a 403 error
        }
    }
 
   return fn
}


// in your router
auth := AuthMiddleware(env, opts)
goji.Use(auth)
```

**Comment by jseguillon** [comment]
Thxs ! Great answers !
