### ISSUE TITLE
How to use this with cji package?

### ISSUE THREAD

**Issue by mdfcorp** [goji/httpauth#9]
I've been trying to set up this middleware with the [cji package](https://github.com/pressly/cji) with no luck. Any hints?

**Comment by elithrar** [comment]
I'm not able to hack up an example myself right now—what have you tried
thus far? If you can post a code snippet/your work in progress and any
error messages I should be able to help.

Since cji just chains middleware I can't see why it wouldn't work from a
quick look at the README.

**Comment by mdfcorp** [comment]
The error I got was: `panic: interface conversion: http.Handler is httpauth.basicAuth, not http.HandlerFunc`. I saw another user showing the same error (and presumably, because we followed the same path) [on the cji Issues](https://github.com/pressly/cji/issues/2).

**Comment by elithrar** [comment]
Can you post the entire code snippet? i.e. your main() function or wherever
your routes/middleware is defined?

**Comment by mdfcorp** [comment]
Sure, here you have:

```golang
package main

import (
	"fmt"
	"net/http"

	"github.com/goji/httpauth"
	"github.com/pressly/cji"
	"github.com/zenazn/goji"
	"github.com/zenazn/goji/web"
)

func ShowHelloWorld(c web.C, w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, world!")
}

func ShowProtected(c web.C, w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "This should be protected!")
}

func main() {
	fnAuth := httpauth.SimpleBasicAuth("dave", "somepassword")

	goji.Get("/", ShowHelloWorld)
	goji.Get("/secured", cji.Use(fnAuth).On(ShowProtected))

	goji.Serve()
}
```

**Comment by patrickdappollonio** [comment]
I'll be keeping an eye here. I think the problem is in `cji` though, rather than in `httpauth`. I've tested a few other Basic HTTP Auth packages and so on, all shows kind of the same message. So [I had to create my own](https://github.com/patrickdappollonio/goji-auth).

**Comment by patrickdappollonio** [comment]
I think it's fair enough to close this issue, because it's not related to `httpauth` per se. @zenazn [offered a solution](https://github.com/pressly/cji/issues/2#issuecomment-82758212) that, when I tested, works with `httpauth`.

**Comment by mdfcorp** [comment]
So we can consider this as closed. Sorry to post it in the wrong place. I should posted it on `cji`.

**Comment by elithrar** [comment]
No problems - glad the issue was discovered nonetheless!
